First Pull Portfolio: setup and mobile version skeleton.
abelagza/Portfolio-setup-and-mobile-version-skeleton pull request #1
Opened 2022-02-17 20:32 UTC by abelagza

## In this Milestone I:

- Created REPO
- Created New Branch and Files
- Updated HTML&CSS files
- Added Linters
- Fixed linter errors locally
- Added Final touches

https://www.loom.com/share/903aae2193f646b091b2ede69b1e7fd4

2022-02-17 21:11 UTC, elmar8287 requested changes
Hi, @abelagza. 

Good job so far!
There are some issues that you still need to work on to go to the next project but you are almost there!

## Required Changes ♻️

- [ ] Check the comments under the review.
- [ ] Please, consider fixing the position of the hamburger icon - it is aligned to the center.

> You version
<img width="290" alt="Screen Shot 2022-02-18 at 01 03 56" src="https://user-images.githubusercontent.com/49064106/154570927-c6b1a85e-f0b4-45b5-8a3a-3aa07472e7cf.png">

- [ ] Please, consider using the required fonts for header `Playfair Display` and for paragraph and button `Poppins`
- [ ] Please, consider that the branch should have a name of a feature or action (e.g. 'created_sidebar' or 'added_comments_section')

## Optional suggestions

- N/A

_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-02-17 21:11 UTC, elmar8287 commented on .github/workflows/linters.yml
> +        run: npx eslint .
- [ ] Please, consider removing the line for JS, as it is not used in this milestone 👍 By doing this, your linter issues will be solved.

2022-02-17 21:11 UTC, elmar8287 commented on README.md
>  ### Prerequisites
- [ ] Please, consider removing the not used section and also adding the instruction on how to set up your project on the local machine, using `git clone` command. It will help to set up your project for other developers.

2022-02-17 21:11 UTC, elmar8287 commented on index.html
> +<!-- header section -->
- [ ] Please, consider removing the comments to make your code more clear 👍

2022-02-17 21:11 UTC, elmar8287 commented on index.html
> +    </section>
- [ ] Please, consider putting this toolbar section into the `header` tag, as required in the project. 
- [ ] Please, consider putting the hamburger icon into the `nav` tag, as required in the project.

2022-02-17 21:11 UTC, elmar8287 commented on index.html
> +                <h1 class="title">Aguilar</h1>
- [ ] Please, consider that you have to use the `h1` tag one time in your code. The `h1` is the main header, which talks to the browser what about is your page.

2022-02-17 21:11 UTC, elmar8287 commented on index.html
> +                    If you like what you see and have a project you need coded, don’t hesitate and contact me.</p>
- [ ] I think it will be better to use the `p` tag one time and insert the whole paragraph 👍

2022-02-17 21:11 UTC, elmar8287 commented on index.html
> +<br><br><br><br><br><br><br><br><br><br><br>
- [ ] It will be better to not use `br` tag and try to fix styling in .css file 👍

2022-02-17 21:11 UTC, elmar8287 commented on index.html
> +    </section>
- [ ] Please, consider that you do not need to implement the footer section on this milestone 👍

2022-02-18 09:29 UTC, abelagza commented
## In this Milestone I:

- Created REPO
- Created New Branch and Files
- Updated HTML&CSS files
- Added Linters
- Fixed linter errors locally
- Added Final touches

**Requested review**

- made review suggested changes

2022-02-18 09:49 UTC, elmar8287 commented
@abelagza you have linter issues, but if you go "Details", you can see that they are not difficult to solve. Please, fix them and submit them again:
<img width="981" alt="Screen Shot 2022-02-18 at 13 46 05" src="https://user-images.githubusercontent.com/49064106/154658607-5f1fb5c0-d09a-47f3-8393-9923c68eb975.png">

If you have any questions, I am here for assistance.

2022-02-18 17:36 UTC, Donard97 requested changes
## Hi @abelagza , 👋 
    
Great work on making the changes requested by a previous reviewer 👏 💯 

You've done well implementing some of the requested changes, but there are still some which aren't addressed yet.
    
## Required Changes ♻️

- [ ]  As the previous reviewer requested please, consider that the branch should have a name of a feature or action (e.g. 'created_sidebar' or 'added_comments_section'). You can use this [link](https://linuxize.com/post/how-to-rename-local-and-remote-git-branch/) for guidance in the future when you want to rename the branch.
- [ ] Please check the comments under the review.
    
 ## Optional suggestions
    
_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._
    
**Cheers and Happy coding!👏👏👏**
    
Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.
    
**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**
    
------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._
 ```

2022-02-18 17:36 UTC, Donard97 commented on index.html
> +                <h1 class="title">Aguilar</h1>
- [ ] Good job on implementing other requested changes but as previous reviewer said kindly consider to use the h1 tag only one time for example in this situation you can put Abel Aguilar inside of only one h1. Keep rocking 💪

2022-02-18 17:36 UTC, Donard97 commented on style.css
> +}
- [ ] You did a tremendous work on designing the first section of you portfolio but please stick as much as you can to [Figma design](https://www.figma.com/file/l7SqJ3ZfkAKih9sFxvWSR4/Microverse-Student-Project-1?node-id=23%3A9) as it was part of [project requirements](https://github.com/microverseinc/curriculum-html-css/blob/main/portfolio/1_setup.md).

Here you have a screenshot of your project:

![image](https://user-images.githubusercontent.com/74506933/154732073-7d5c5929-9979-46bf-9a51-69d1b8dc13ba.png)

Here you have a screenshot of the design:

![image](https://user-images.githubusercontent.com/74506933/154732184-dbbe4452-cc14-41bc-ad6e-4a9f2cf1bc79.png)

2022-02-18 17:54 UTC, closed without merging